# Introducción a numpy

In [1]:
import numpy as np 

In [2]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [4]:
a = np.array([10, 20, 24, 5, 15, 50, 120])
a[4]

15

In [5]:
a[3:]

array([  5,  15,  50, 120])

In [6]:
a[3:7]

array([  5,  15,  50, 120])

In [7]:
a[1::4]

array([20, 50])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [16]:
b= np.array([['x','y','z'], ['a','c','b']])
b

array([['x', 'y', 'z'],
       ['a', 'c', 'b']], dtype='<U1')

In [17]:
b.ndim

2

In [19]:
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [21]:
headers = [('nombre','S10'), ('edad', int), ('nacionalidad','S100')]
data = [('Amelie',21,'Francesa'), 
         ('Valerie', 30,'Canadiense'),
         ('Valentina',25,'Inglesa'),
         ('Alejandra',22,'Cubana')]
users = np.array(data, dtype=headers)

np.sort(users, order='edad')

array([(b'Amelie', 21, b'Francesa'), (b'Alejandra', 22, b'Cubana'),
       (b'Valentina', 25, b'Inglesa'), (b'Valerie', 30, b'Canadiense')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('nacionalidad', 'S100')])

In [22]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [26]:
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [27]:
np.diag([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])